### PR TITLE
Help screen filetype txt

### PR DESCRIPTION
**Pull request by Defalt36**

### CODE REVIEW

**Comment by connorhsm** [comment]
Similar to what I said in #27
We need information about what this change is and why it is needed before we can review it.

**Comment by Defalt36** [comment]
> Similar to what I said in #27
> We need information about what this change is and why it is needed before we can review it.

kripts requested it. he said it was causing issues.
risvh said it was because the file was not a text file, so that's it I changed.

**Review by connorhsm — APPROVED** [review]
Thanks for the comments, just make sure to add these details into pull requests for documentation reasons and to keep others informed who may not have been involved in the discussions.

**Comment by connorhsm** [comment]
@Defalt36 If you could please resolve the conflict and request my review again, I'll merge.

**Pull request merged**
