### PR TITLE
Update FUNDING.yml

### PR DESCRIPTION
**Pull request by connorhsm**

### CODE REVIEW

**Review by 0xAdk — APPROVED** [review]

**Comment by 0xAdk** [comment]
I assume you have to merge it into master before it updates on the sidebar right?

**Comment by connorhsm** [comment]
Yes, you're always welcome to merge if you're the approver.

**Comment by 0xAdk** [comment]
I think the button was grayed out, so I don't think I could

**Comment by connorhsm** [comment]
Weird. Everything I can see says you should have been able to.

**Pull request merged**
