### PR TITLE
Reverting this change as it changes how auto-generated obejcts (e.g. useDummies) are numbered.

### LINKED ISSUE #5: Wrong sprites for use dummy objects
#2 
This merge caused some use dummy objects (tools and stackable items for example) to be drawn with the wrong sprites. Reverting the change in this line (linked below) does fix the problem, probably a bad fix tho without knowing what actually caused the bug.

https://github.com/twohoursonelife/OneLife/commit/a5562af18431300db56507c327dd77b60b837e37#diff-f95b96883041b8b926e300c9b58f9e8aR2506

### PR DESCRIPTION
**Pull request by risvh**
The change appeared in 
https://github.com/twohoursonelife/OneLife/commit/a5562af18431300db56507c327dd77b60b837e37

Related issue:
https://github.com/twohoursonelife/OneLife/issues/5

### CODE REVIEW

**Comment by kripts** [comment]
Tested and seems to be the fix

**Comment by connorhsm** [comment]
How did this change improve loading time and will reverting it negatively impact loading times again?

**Comment by connorhsm** [comment]
From reviewing #5 , I understand that this is a compatibility change and that we're happy to forefeit some of the improved loading time for this compaitiblity? Is that correct?

**Comment by risvh** [comment]
The change reverting doesn't have impact on the loading time as I tested it.

**Review by connorhsm — APPROVED** [review]
Puzzeled as to why then it was inisisted that we take the time to cherry pick the change that we're reverting.

Approved.

**Pull request merged**
