### PR TITLE
Nude setting

### PR DESCRIPTION
**Pull request by Adk9p**
Created toggleable box in settings to change if character is nude or not, requires restart on change

### CODE REVIEW

**Comment by connorhsm** [comment]
> What is the need to change the default fullscreen and borderless settings?

Not sure about the whole commit **adacca6**
How come the pullAndBuildLatest was removed?

**Comment by Adk9p** [comment]
Oh pullAndBuildLatest was on accident, I did rm OneLife_ * to clean up the folder

fullscreen is default on, but I saw on some machines vsync didn't work so turning on borderless fixes that

**Comment by Adk9p** [comment]
Looking back I agree removing it entirely would be better as it doesn't have anything to do with the branch.

**Comment by connorhsm** [comment]
There is too much mess here, including unrelated commits and unnecessary formatting.
Please make your changes on a fresh fork and resubmit the request.

**Pull request closed without merging**
